### ISSUE TITLE
Custom actions with hotkey and context menu

### ISSUE THREAD

**Issue by Pugsworth** [Torrunt/vimage#24]
Would be pretty cool if you could create custom actions to use commands on the image.

Example:
You could make a context menu entry to upload the image using whatever program you want, and/or assign a hotkey for it.
e.g.

```
CustomEntries = {
    Upload : "sharex.exe %f"
}

ContextMenu = {
        ...
    Upload : CustomEntries.Upload
}
```

Pseudocode, but you should get the gist.

This would make Vimage much more robust since you could add any action for images, right from vimage.

**Comment by Torrunt** [comment]
Finally decided to had a crack at adding this. https://github.com/Torrunt/vimage/commit/b03b212534cce67d77593de143f440ec7ac2abcd

At the moment you can only add the custom actions in the config.txt. Next I'll add a new tab in vimage_settings.exe to easily add and delete them. Should probably make it possible to bind them to keys too. I might add the key binding for them in the new tab rather than make them populate the controls tab... not sure yet though.


Here's an example of some custom actions you can do:
```
CustomActions =
{
	EDIT : %windir%\system32\mspaint.exe %f
	EDIT_PAINT.NET : "C:\Program Files\Paint.NET\PaintDotNet.exe" %f
	SHAREX : "C:\Program Files\ShareX\ShareX.exe" %f
}
```
They all simply open the current image in whatever program. Though what other commands could you possibly do with an image file?

**Comment by Torrunt** [comment]
You can now add and delete custom actions via vimage_settings.exe https://github.com/Torrunt/vimage/commit/446e16f09415ab5126bf50cfb1eb467ed9660bdd

**Comment by Torrunt** [comment]
Fixed it up a bit to allow for multiple arguments https://github.com/Torrunt/vimage/commit/10caddabd3740db9c13b3d7b7af6404f5cc13dc3

Also added a %d value to get the current directory https://github.com/Torrunt/vimage/commit/153bcf6dfea27b146c97601fa976ebdf3cef2832

Here's an example of a possible command you can do that takes multiple arguments and uses %d:
> "C:\Program Files\nConvert\nconvert.exe" -out jpeg -resize 50% 50% -o "%d\blahblah%.jpg" %f

It uses nConvert to create a new version of the file called blahblah#.jpg at 50% of the size (the % that gives the file an incremental number is part of nConvert).

**Comment by Torrunt** [comment]
You can now bind custom actions to keys https://github.com/Torrunt/vimage/commit/0486f9616aaec3b374f47e926eab7ecb2e7b893d

Custom actions are now also added to the bottom of the vimage_settings.exe controls tab https://github.com/Torrunt/vimage/commit/5fbc4d4b3fdb7f071df4cff18ffd23afe04b7092
