### ISSUE TITLE
Some gifs play very laggy.

### ISSUE THREAD

**Issue by ghost** [Torrunt/vimage#45]
Not sure why this happens.
<a href=https://streamable.com/p582s>Comparation</a>
<img alt="File" src=https://cdn.discordapp.com/attachments/567432560423075866/587625967325937686/tumblr_pko09f2v2b1roqda3o1_640.gif>

**Comment by Torrunt** [comment]
It's probably failing to grab the proper frame duration for the file. Maybe there is a better way to get it... Or at the very least I could add a way to easily adjust the frame rate of whatever animated image you're viewing.

https://github.com/Torrunt/vimage/blob/master/vimage/Source/Display/Graphics.cs#L342

**Comment by Torrunt** [comment]
I randomly decided to do a little work on vimage today and managed to fix this issue. Was actually pretty simple.

The problem was due to vimage only using the frame delay of the first frame. Animated gifs can actually have different frame delays for each frame. It now uses the correct frame delay for each frame (if provided): https://github.com/Torrunt/vimage/blob/master/vimage/Source/Display/Graphics.cs#L523

The example gif @ghost provided now plays smoothly in vimage!

![slowgif](https://user-images.githubusercontent.com/830354/120889952-5f08aa80-c632-11eb-8f88-ff95b8d8a4de.gif)
